from .sft import SFTLoss as SFTLoss
from .orpo import ORPOLoss as ORPOLoss
from .dpo import DPOLoss as DPOLoss
from .simpo import SimPOLoss as SimPOLoss
from .kto import KTOLoss as KTOLoss
from .cpo import CPOLoss as CPOLoss
from .ipo import IPOLoss as IPOLoss
from .online import OnlineMethod as OnlineMethod
from .grpo import GRPOMethod as GRPOMethod
from .rloo import RLOOMethod as RLOOMethod
from .online_dpo import OnlineDPOMethod as OnlineDPOMethod
from .raft import RAFTMethod as RAFTMethod
from .reward import RewardModelLoss as RewardModelLoss
